name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
      - name: setup
        uses: actions/setup-node@v2
        with:    
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm install

      - name: Test Script
        run: npm test

      - name: Run Script
        run: npm run build

      - name: Setup Welcome
        run: echo A WebClient Project!
